version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/raknet_go"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/raknet_rs"
    schedule:
      interval: "weekly"
