name: MacOS Go Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture:
          - amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "^1.21.5"
          architecture: ${{ matrix.architecture }}

      - name: Version
        run: go version

      - name: Install dependencies
        run: |
          cd raknet_go
          go get -u github.com/sandertv/go-raknet

      - name: Build
        run: |
          cd build
          cd go
          bash build.sh go-raknet.dylib

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: raknet-${{ matrix.architecture }}
          path: raknet_go/go-raknet.dylib
