name: Windows C++ Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        architecture:
          - amd64
          - amd64_x86

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}

      - name: Build
        run: |
          cd build
          cd cpp
          .\build.bat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raknet-${{ matrix.architecture }}
          path: build/cpp/raknet.dll
